"""
role_data.py — Per-class content pools for 25 IT professions
=============================================================

Each role has unique: skills, projects, responsibilities, summary.
This is what makes resumes distinguishable across classes.
"""

ROLE_DATA = {
    "Data Scientist": {
        "skills": [
            "scikit-learn", "XGBoost", "LightGBM", "Pandas", "NumPy", "SciPy",
            "R", "Jupyter Notebooks", "feature engineering", "A/B testing",
            "statistical modeling", "hypothesis testing", "regression analysis",
            "classification algorithms", "clustering", "dimensionality reduction",
            "data wrangling", "exploratory data analysis", "Matplotlib", "Seaborn",
            "Bayesian inference", "time series forecasting", "survival analysis",
        ],
        "projects": [
            "Built customer churn prediction model using gradient boosting achieving 92% AUC",
            "Developed A/B testing framework that reduced experiment cycle time by 40%",
            "Created demand forecasting pipeline using ARIMA and Prophet models",
            "Designed feature store serving 200+ ML features across 15 data science teams",
            "Built recommendation system using collaborative filtering for e-commerce platform",
            "Developed fraud detection system processing 1M+ transactions daily",
            "Created customer segmentation model using K-means and DBSCAN clustering",
            "Built NLP pipeline for sentiment analysis of product reviews",
        ],
        "responsibilities": [
            "Performed exploratory data analysis on multi-terabyte datasets",
            "Built and validated predictive models for business stakeholders",
            "Conducted A/B tests and analyzed statistical significance of results",
            "Created automated reporting dashboards for executive leadership",
            "Collaborated with product teams to define success metrics and KPIs",
            "Mentored junior data scientists on statistical best practices",
        ],
        "summary": "Analytical professional with deep expertise in statistical modeling, machine learning, and data-driven decision making",
    },

    "Software Engineer": {
        "skills": [
            "Java", "C++", "Go", "system design", "object-oriented programming",
            "design patterns", "algorithms", "data structures", "multithreading",
            "concurrency", "JUnit", "Maven", "Gradle", "code review",
            "software architecture", "SOLID principles", "clean code",
            "distributed computing", "version control", "technical documentation",
            "debugging", "performance profiling", "memory management",
        ],
        "projects": [
            "Architected distributed task scheduling system handling 50K jobs per hour",
            "Refactored legacy monolith into modular service architecture reducing tech debt by 60%",
            "Implemented thread-safe caching layer reducing database load by 70%",
            "Built custom serialization framework 3x faster than standard JSON parsing",
            "Designed plugin architecture enabling third-party extensions",
            "Created automated code review bot integrated with CI pipeline",
            "Developed real-time event processing engine using producer-consumer pattern",
            "Built high-performance data ingestion service processing 100K events per second",
        ],
        "responsibilities": [
            "Designed and implemented core platform services used by 50+ engineers",
            "Led code review process ensuring code quality and adherence to standards",
            "Optimized critical path algorithms reducing latency by 45%",
            "Authored technical design documents for cross-team architecture decisions",
            "Debugged complex production issues in distributed systems",
            "Mentored junior engineers through pair programming sessions",
        ],
        "summary": "Experienced engineer focused on building robust, scalable software systems with clean architecture and strong engineering practices",
    },

    "Web Developer": {
        "skills": [
            "HTML5", "CSS3", "JavaScript", "PHP", "WordPress", "jQuery",
            "Bootstrap", "responsive design", "SEO optimization", "SASS",
            "web accessibility", "cross-browser compatibility", "Webpack",
            "web performance optimization", "Progressive Web Apps", "HTTP protocols",
            "DNS management", "SSL certificates", "cPanel", "web hosting",
            "Google Analytics", "page speed optimization", "lazy loading",
        ],
        "projects": [
            "Built responsive e-commerce website serving 50K monthly visitors",
            "Developed custom WordPress theme with page load time under 2 seconds",
            "Created Progressive Web App with offline functionality and push notifications",
            "Redesigned corporate website improving Core Web Vitals scores by 60%",
            "Built landing page optimization system increasing conversion rates by 35%",
            "Developed multi-language website supporting 8 locales with RTL support",
            "Created interactive portfolio website with CSS animations and parallax scrolling",
            "Built client booking system with calendar integration and payment processing",
        ],
        "responsibilities": [
            "Developed and maintained responsive websites for 20+ client projects",
            "Optimized page load speeds and Core Web Vitals for SEO ranking improvement",
            "Implemented SEO best practices increasing organic search traffic by 40%",
            "Ensured WCAG 2.1 accessibility compliance across all web properties",
            "Managed domain registrations, SSL certificates, and hosting configurations",
            "Created pixel-perfect implementations from Figma and Photoshop designs",
        ],
        "summary": "Creative web professional skilled in building fast, accessible, and SEO-optimized websites with modern web technologies",
    },

    "DevOps Engineer": {
        "skills": [
            "Terraform", "Ansible", "Jenkins", "GitHub Actions", "Docker",
            "Kubernetes", "Helm", "Prometheus", "Grafana", "ELK Stack",
            "infrastructure as code", "CI/CD pipelines", "shell scripting",
            "configuration management", "container orchestration", "service mesh",
            "Istio", "ArgoCD", "HashiCorp Vault", "Packer",
            "site reliability engineering", "incident management", "runbook automation",
        ],
        "projects": [
            "Built zero-downtime deployment pipeline serving 99.99% uptime SLA",
            "Migrated infrastructure from manual provisioning to Terraform modules",
            "Implemented GitOps workflow using ArgoCD reducing deployment time from hours to minutes",
            "Created self-healing Kubernetes cluster with automated pod recovery",
            "Built centralized logging platform processing 500GB logs daily using ELK Stack",
            "Designed disaster recovery system with automated failover across regions",
            "Implemented secrets management solution using HashiCorp Vault",
            "Created infrastructure monitoring dashboard with custom Prometheus exporters",
        ],
        "responsibilities": [
            "Designed and maintained CI/CD pipelines for 30+ microservices",
            "Managed Kubernetes clusters across development, staging, and production environments",
            "Automated infrastructure provisioning using Terraform and Ansible playbooks",
            "Monitored system health using Prometheus and Grafana alert dashboards",
            "Responded to production incidents and conducted post-mortem analysis",
            "Reduced deployment frequency from weekly to multiple times daily",
        ],
        "summary": "Infrastructure specialist focused on automation, reliability, and continuous delivery of scalable production systems",
    },

    "ML Engineer": {
        "skills": [
            "TensorFlow", "PyTorch", "MLflow", "Kubeflow", "model serving",
            "ONNX", "TensorRT", "model optimization", "feature stores",
            "ML pipelines", "experiment tracking", "model monitoring",
            "distributed training", "Horovod", "Ray", "model versioning",
            "hyperparameter tuning", "Optuna", "Weights and Biases",
            "model compression", "quantization", "edge deployment",
            "batch inference", "real-time inference",
        ],
        "projects": [
            "Built end-to-end ML pipeline processing 10M training samples daily using Kubeflow",
            "Deployed real-time model serving infrastructure handling 5K predictions per second",
            "Implemented A/B testing framework for model comparison in production",
            "Created automated model retraining pipeline triggered by data drift detection",
            "Optimized deep learning model inference latency from 200ms to 15ms using TensorRT",
            "Built feature store serving 500+ features with sub-millisecond latency",
            "Designed distributed training setup across 8 GPUs reducing training time by 6x",
            "Implemented model monitoring system detecting performance degradation in real-time",
        ],
        "responsibilities": [
            "Productionized machine learning models from research notebooks to scalable services",
            "Built and maintained ML infrastructure supporting 20+ model deployments",
            "Optimized model inference latency and throughput for production workloads",
            "Implemented automated model retraining and deployment pipelines",
            "Collaborated with data scientists to translate prototypes into production systems",
            "Managed experiment tracking and model versioning using MLflow",
        ],
        "summary": "ML infrastructure specialist focused on deploying, scaling, and monitoring machine learning models in production environments",
    },

    "Data Analyst": {
        "skills": [
            "Excel", "SQL", "Tableau", "Power BI", "Google Data Studio",
            "data visualization", "pivot tables", "VLOOKUP", "dashboard design",
            "reporting automation", "data cleaning", "descriptive statistics",
            "trend analysis", "cohort analysis", "funnel analysis",
            "Google Sheets", "business intelligence", "data storytelling",
            "KPI tracking", "ad hoc analysis", "stakeholder reporting",
        ],
        "projects": [
            "Created executive dashboard tracking 50+ KPIs across 8 business units",
            "Built automated weekly reporting system reducing manual effort by 80%",
            "Developed customer funnel analysis identifying 25% drop-off improvement opportunity",
            "Created interactive Tableau dashboard for real-time sales performance monitoring",
            "Built cohort analysis framework revealing customer retention patterns",
            "Designed data quality monitoring dashboard flagging anomalies automatically",
            "Created supply chain analytics report saving $2M in inventory costs",
            "Developed marketing attribution model tracking ROI across 12 channels",
        ],
        "responsibilities": [
            "Created and maintained business intelligence dashboards for executive team",
            "Performed ad hoc analysis to support strategic business decisions",
            "Automated recurring reports saving 15 hours of manual work per week",
            "Cleaned and transformed raw data from multiple sources for analysis",
            "Presented data-driven insights to non-technical stakeholders",
            "Defined and tracked key performance indicators across departments",
        ],
        "summary": "Detail-oriented analyst skilled in turning raw data into actionable business insights through visualization and reporting",
    },

    "Backend Developer": {
        "skills": [
            "Node.js", "Express.js", "Django", "Flask", "Spring Boot",
            "REST API design", "GraphQL", "microservices architecture",
            "PostgreSQL", "MongoDB", "Redis", "RabbitMQ", "Kafka",
            "API gateway", "authentication", "OAuth2", "JWT tokens",
            "database optimization", "query tuning", "connection pooling",
            "rate limiting", "caching strategies", "message queues",
        ],
        "projects": [
            "Built RESTful API serving 10M requests daily with sub-100ms response time",
            "Designed microservices architecture breaking monolith into 12 independent services",
            "Implemented real-time notification system using WebSockets and Redis pub/sub",
            "Created OAuth2 authentication service supporting Google, GitHub, and SAML providers",
            "Built event-driven order processing pipeline using Kafka and consumer groups",
            "Designed database sharding strategy handling 500M+ records across 8 shards",
            "Implemented rate limiting and throttling system protecting APIs from abuse",
            "Created GraphQL gateway aggregating data from 6 downstream microservices",
        ],
        "responsibilities": [
            "Designed and implemented RESTful APIs following OpenAPI specification standards",
            "Optimized database queries reducing average response time by 60%",
            "Implemented caching strategies using Redis reducing database load by 50%",
            "Built authentication and authorization middleware securing all API endpoints",
            "Managed message queue infrastructure for asynchronous task processing",
            "Wrote comprehensive API documentation and integration guides",
        ],
        "summary": "Server-side specialist focused on building high-performance APIs, microservices, and database-driven backend systems",
    },

    "Frontend Developer": {
        "skills": [
            "React", "Vue.js", "Angular", "TypeScript", "Next.js",
            "CSS Grid", "Flexbox", "styled-components", "Tailwind CSS",
            "state management", "Redux", "Vuex", "component libraries",
            "Storybook", "responsive design", "accessibility", "ARIA",
            "browser DevTools", "performance profiling", "lazy loading",
            "code splitting", "single page applications", "web animations",
        ],
        "projects": [
            "Built component library with 60+ reusable React components used across 5 products",
            "Developed real-time collaborative editing interface using WebSockets and CRDT",
            "Created accessible design system achieving WCAG 2.1 AAA compliance",
            "Built interactive data visualization dashboard using D3.js and React",
            "Implemented micro-frontend architecture enabling independent team deployments",
            "Developed drag-and-drop workflow builder with complex state management",
            "Created server-side rendered Next.js application improving SEO and load times",
            "Built offline-capable Progressive Web App with service worker caching",
        ],
        "responsibilities": [
            "Built and maintained reusable UI component library in React with TypeScript",
            "Implemented pixel-perfect responsive layouts from Figma design specifications",
            "Optimized frontend bundle size reducing initial load time by 50%",
            "Ensured accessibility compliance with screen reader testing and ARIA attributes",
            "Managed complex application state using Redux with middleware patterns",
            "Conducted frontend performance audits using Lighthouse and Chrome DevTools",
        ],
        "summary": "UI specialist focused on building fast, accessible, and maintainable frontend applications with modern JavaScript frameworks",
    },

    "Full Stack Developer": {
        "skills": [
            "MERN stack", "Next.js", "Express.js", "React", "MongoDB",
            "PostgreSQL", "REST APIs", "GraphQL", "authentication flows",
            "deployment automation", "Vercel", "Netlify", "Heroku",
            "end-to-end testing", "Cypress", "full lifecycle development",
            "database design", "server-side rendering", "client-side routing",
            "payment integration", "Stripe", "third-party API integration",
        ],
        "projects": [
            "Built SaaS platform from scratch handling 10K users with React frontend and Node backend",
            "Developed real-time marketplace application with bidding system and payment processing",
            "Created multi-tenant project management tool with role-based access control",
            "Built social media platform with real-time feeds, messaging, and notification system",
            "Developed e-learning platform with video streaming, quizzes, and progress tracking",
            "Created inventory management system with barcode scanning and reporting",
            "Built appointment scheduling platform with calendar sync and automated reminders",
            "Developed customer portal with self-service account management and billing",
        ],
        "responsibilities": [
            "Developed complete features from database schema to frontend UI components",
            "Built and deployed full-stack applications on cloud platforms end-to-end",
            "Implemented authentication flows with social login and multi-factor authentication",
            "Integrated third-party APIs including Stripe payments and SendGrid email",
            "Managed database migrations and schema evolution across releases",
            "Wrote end-to-end tests using Cypress covering critical user journeys",
        ],
        "summary": "Versatile developer experienced in building complete web applications from database design through frontend delivery",
    },

    "Database Administrator": {
        "skills": [
            "Oracle Database", "MySQL", "PostgreSQL", "SQL Server",
            "database tuning", "query optimization", "execution plans",
            "indexing strategies", "partitioning", "replication",
            "backup and recovery", "point-in-time recovery", "disaster recovery",
            "database security", "encryption at rest", "audit logging",
            "stored procedures", "database migration", "schema design",
            "high availability", "failover clustering", "connection management",
        ],
        "projects": [
            "Migrated 5TB Oracle database to PostgreSQL with zero downtime cutover",
            "Implemented read replica architecture reducing primary database load by 60%",
            "Designed automated backup system with 15-minute recovery point objective",
            "Created database performance monitoring dashboard tracking slow query patterns",
            "Implemented table partitioning strategy improving query performance by 80%",
            "Built automated database provisioning for development and staging environments",
            "Designed multi-region replication setup for disaster recovery compliance",
            "Created index optimization scripts reducing storage usage by 30%",
        ],
        "responsibilities": [
            "Administered production database clusters serving mission-critical applications",
            "Optimized slow queries and created indexing strategies for performance improvement",
            "Managed backup schedules and tested recovery procedures monthly",
            "Implemented database security policies including encryption and access controls",
            "Planned and executed database version upgrades with minimal downtime",
            "Monitored database health metrics and capacity planning for growth",
        ],
        "summary": "Database specialist focused on performance tuning, high availability, and data integrity for enterprise database systems",
    },

    "System Administrator": {
        "skills": [
            "Linux administration", "Windows Server", "Active Directory",
            "Group Policy", "shell scripting", "Bash", "PowerShell",
            "patch management", "LDAP", "DNS", "DHCP",
            "VMware", "Hyper-V", "virtualization", "storage management",
            "NFS", "CIFS", "system monitoring", "Nagios", "Zabbix",
            "backup solutions", "disaster recovery planning", "user management",
        ],
        "projects": [
            "Deployed Active Directory infrastructure serving 5000+ users across 3 locations",
            "Implemented automated patch management system for 500+ servers",
            "Migrated physical servers to VMware virtualization reducing hardware costs by 50%",
            "Built centralized log management system using Syslog and Nagios monitoring",
            "Created automated user provisioning and deprovisioning scripts in PowerShell",
            "Designed and implemented backup strategy with offsite replication",
            "Deployed SCCM for software distribution and compliance reporting",
            "Implemented Group Policy objects standardizing desktop configurations",
        ],
        "responsibilities": [
            "Managed Linux and Windows server infrastructure across production environments",
            "Administered Active Directory including user accounts, groups, and policies",
            "Automated routine system administration tasks using Bash and PowerShell scripts",
            "Monitored system performance and responded to alerts using Nagios and Zabbix",
            "Managed VMware ESXi hosts and virtual machine lifecycle operations",
            "Maintained documentation for system configurations and runbook procedures",
        ],
        "summary": "Infrastructure administrator experienced in managing enterprise server environments with focus on automation and reliability",
    },

    "Network Engineer": {
        "skills": [
            "Cisco IOS", "Juniper", "routing protocols", "OSPF", "BGP",
            "MPLS", "VLANs", "switching", "firewalls", "VPN",
            "TCP/IP", "subnetting", "network monitoring", "Wireshark",
            "load balancing", "F5", "network security", "ACLs",
            "SD-WAN", "wireless networking", "QoS", "SNMP",
            "network troubleshooting", "packet analysis",
        ],
        "projects": [
            "Designed and deployed enterprise WAN connecting 20 branch offices using MPLS",
            "Implemented SD-WAN solution reducing bandwidth costs by 40%",
            "Built redundant firewall architecture with automated failover under 5 seconds",
            "Designed campus network architecture supporting 10,000+ concurrent wireless clients",
            "Implemented network segmentation using VLANs and ACLs for PCI compliance",
            "Deployed network monitoring solution providing real-time visibility across 500+ devices",
            "Migrated legacy network to spine-leaf architecture for data center modernization",
            "Implemented QoS policies prioritizing video conferencing and VoIP traffic",
        ],
        "responsibilities": [
            "Designed and maintained enterprise network infrastructure across multiple sites",
            "Configured and managed Cisco routers, switches, and firewall appliances",
            "Troubleshot complex network issues using Wireshark and packet capture analysis",
            "Implemented network security policies including firewall rules and VPN configurations",
            "Monitored network performance and capacity planning using SNMP-based tools",
            "Documented network topology diagrams and maintained configuration standards",
        ],
        "summary": "Network specialist experienced in designing, implementing, and managing enterprise routing, switching, and security infrastructure",
    },

    "Cybersecurity Analyst": {
        "skills": [
            "SIEM", "Splunk", "penetration testing", "vulnerability assessment",
            "incident response", "SOC operations", "threat hunting",
            "Nessus", "Burp Suite", "Metasploit", "OWASP Top 10",
            "security compliance", "ISO 27001", "NIST framework",
            "malware analysis", "digital forensics", "phishing detection",
            "endpoint detection", "CrowdStrike", "security auditing",
            "risk assessment", "security awareness training",
        ],
        "projects": [
            "Built SOC monitoring platform processing 100K security events per minute in Splunk",
            "Conducted penetration testing for 30+ web applications identifying critical vulnerabilities",
            "Implemented zero-trust network architecture reducing attack surface by 70%",
            "Created automated threat detection rules catching 95% of phishing attempts",
            "Developed incident response playbook reducing mean time to respond from 4 hours to 30 minutes",
            "Built vulnerability management program scanning 2000+ assets weekly",
            "Implemented DLP solution preventing sensitive data exfiltration across endpoints",
            "Conducted red team exercises simulating advanced persistent threat scenarios",
        ],
        "responsibilities": [
            "Monitored SIEM dashboards and investigated security alerts in real-time",
            "Conducted vulnerability assessments and penetration tests on production systems",
            "Led incident response efforts for security breaches and data leaks",
            "Performed threat hunting analysis to identify advanced persistent threats",
            "Created security policies and ensured compliance with regulatory requirements",
            "Delivered security awareness training to employees across the organization",
        ],
        "summary": "Security professional specialized in threat detection, vulnerability assessment, and incident response for enterprise environments",
    },

    "Cloud Architect": {
        "skills": [
            "AWS Solutions Architect", "Azure", "GCP", "cloud migration",
            "serverless", "Lambda", "CloudFormation", "ARM templates",
            "multi-cloud strategy", "cost optimization", "FinOps",
            "cloud networking", "VPC design", "IAM policies",
            "S3", "DynamoDB", "cloud security", "Well-Architected Framework",
            "auto-scaling", "elastic load balancing", "cloud governance",
            "landing zones", "account management",
        ],
        "projects": [
            "Designed multi-region AWS architecture achieving 99.999% availability",
            "Led cloud migration of 200+ applications from on-premise to AWS saving $3M annually",
            "Implemented FinOps practices reducing cloud spend by 35% through right-sizing",
            "Designed serverless data processing pipeline handling 1M events per hour",
            "Created cloud landing zone with automated account provisioning and guardrails",
            "Built hybrid cloud architecture connecting on-premise data center to AWS via Direct Connect",
            "Implemented cloud security baseline with automated compliance checking",
            "Designed multi-account AWS organization structure with centralized logging",
        ],
        "responsibilities": [
            "Designed cloud architecture solutions aligned with Well-Architected Framework",
            "Led cloud migration programs evaluating workload suitability and migration strategies",
            "Implemented IAM policies and security guardrails across cloud accounts",
            "Optimized cloud costs through reserved instances, spot instances, and right-sizing",
            "Created cloud architecture standards and reference architectures for engineering teams",
            "Conducted architecture reviews ensuring designs meet scalability and security requirements",
        ],
        "summary": "Cloud specialist focused on designing scalable, cost-effective, and secure multi-cloud architectures for enterprise workloads",
    },

    "QA Engineer": {
        "skills": [
            "Selenium", "Cypress", "test automation", "test planning",
            "bug tracking", "Jira", "regression testing", "JUnit", "TestNG",
            "API testing", "Postman", "load testing", "JMeter",
            "test case design", "boundary value analysis", "equivalence partitioning",
            "continuous testing", "BDD", "Cucumber", "Gherkin",
            "mobile testing", "Appium", "performance testing",
        ],
        "projects": [
            "Built automated test suite with 2000+ test cases achieving 85% code coverage",
            "Implemented continuous testing pipeline reducing regression cycle from 3 days to 4 hours",
            "Created API testing framework validating 500+ endpoints with automated schema checks",
            "Built load testing infrastructure simulating 50K concurrent users using JMeter",
            "Developed BDD test framework using Cucumber enabling business-readable test specifications",
            "Created visual regression testing system catching UI inconsistencies automatically",
            "Built cross-browser testing matrix covering 12 browser and device combinations",
            "Implemented shift-left testing strategy reducing production defects by 60%",
        ],
        "responsibilities": [
            "Designed and executed test plans for feature releases and regression cycles",
            "Created and maintained automated test suites using Selenium and Cypress",
            "Performed API testing and validation using Postman and custom test scripts",
            "Tracked and managed defects through complete lifecycle in Jira",
            "Conducted load and performance testing identifying bottlenecks before production",
            "Collaborated with developers to define acceptance criteria and test coverage goals",
        ],
        "summary": "Quality assurance specialist focused on test automation, continuous testing, and defect prevention across the software development lifecycle",
    },

    "Mobile App Developer": {
        "skills": [
            "Swift", "Kotlin", "React Native", "Flutter", "Dart",
            "iOS development", "Android development", "Xcode", "Android Studio",
            "mobile UI design", "Core Data", "Room database", "SQLite",
            "push notifications", "Firebase", "App Store deployment",
            "Google Play deployment", "mobile analytics", "Crashlytics",
            "gesture handling", "deep linking", "in-app purchases",
        ],
        "projects": [
            "Built iOS fitness tracking app with 500K downloads and HealthKit integration",
            "Developed cross-platform food delivery app using Flutter serving 50K daily orders",
            "Created React Native social networking app with real-time chat and media sharing",
            "Built offline-first note-taking app with cloud sync using Core Data and CloudKit",
            "Developed AR shopping experience using ARKit allowing virtual product placement",
            "Created mobile banking app with biometric authentication and transaction history",
            "Built location-based service app with geofencing and real-time map features",
            "Developed mobile game with in-app purchases and leaderboard system",
        ],
        "responsibilities": [
            "Developed native iOS and Android applications from design to App Store release",
            "Implemented responsive mobile UI layouts following platform-specific design guidelines",
            "Integrated push notifications and Firebase analytics for user engagement tracking",
            "Managed App Store and Google Play submission process and release cycles",
            "Optimized app performance including memory management and battery consumption",
            "Implemented offline data persistence and background sync mechanisms",
        ],
        "summary": "Mobile specialist experienced in building native and cross-platform mobile applications for iOS and Android platforms",
    },

    "Business Analyst": {
        "skills": [
            "requirements gathering", "stakeholder management", "process modeling",
            "BPMN", "user stories", "use case diagrams", "wireframing",
            "gap analysis", "cost-benefit analysis", "SWOT analysis",
            "Visio", "Lucidchart", "Confluence", "Jira",
            "acceptance criteria", "UAT coordination", "data mapping",
            "business process reengineering", "change management",
            "requirements traceability", "functional specifications",
        ],
        "projects": [
            "Led requirements analysis for ERP system implementation across 5 departments",
            "Created process maps identifying 12 automation opportunities saving 500 labor hours monthly",
            "Developed business case securing $2M budget for digital transformation initiative",
            "Facilitated stakeholder workshops gathering requirements from 40+ business users",
            "Created functional specifications for CRM migration affecting 200+ users",
            "Designed to-be process flows reducing order processing time by 45%",
            "Led UAT coordination for billing system upgrade with 300+ test scenarios",
            "Developed requirements traceability matrix linking 500+ requirements to test cases",
        ],
        "responsibilities": [
            "Gathered and documented business requirements through stakeholder interviews",
            "Created user stories and acceptance criteria for agile development teams",
            "Facilitated workshops and JAD sessions with cross-functional stakeholders",
            "Performed gap analysis between current state and desired business capabilities",
            "Coordinated user acceptance testing and managed defect resolution",
            "Maintained requirements traceability matrix from elicitation through deployment",
        ],
        "summary": "Business analysis professional skilled in requirements engineering, process improvement, and bridging business needs with technical solutions",
    },

    "IT Project Manager": {
        "skills": [
            "Agile methodology", "Scrum Master", "Kanban", "PMP certification",
            "project planning", "risk management", "stakeholder communication",
            "Jira", "MS Project", "Confluence", "Smartsheet",
            "resource allocation", "budget management", "earned value management",
            "sprint planning", "velocity tracking", "burndown charts",
            "vendor management", "project portfolio management",
            "change control", "scope management",
        ],
        "projects": [
            "Managed $5M ERP implementation delivered on time across 3 countries",
            "Led Agile transformation for 8 development teams transitioning from Waterfall",
            "Coordinated platform migration project involving 15 cross-functional teams",
            "Managed vendor selection and onboarding for $1.5M outsourcing engagement",
            "Delivered data warehouse project 2 weeks ahead of schedule under budget",
            "Led program of 5 concurrent projects with combined team of 40+ resources",
            "Implemented project governance framework adopted across the PMO organization",
            "Managed security compliance project achieving SOC 2 certification in 6 months",
        ],
        "responsibilities": [
            "Managed project timelines, budgets, and resource allocation across multiple workstreams",
            "Facilitated sprint planning, daily standups, and retrospective meetings",
            "Created and maintained project schedules with milestone tracking and dependencies",
            "Communicated project status and risks to executive sponsors and steering committees",
            "Managed scope changes through formal change control process",
            "Coordinated cross-functional team dependencies and resolved blockers",
        ],
        "summary": "Project management professional experienced in leading complex technology projects using Agile and traditional methodologies",
    },

    "UI UX Designer": {
        "skills": [
            "Figma", "Sketch", "Adobe XD", "wireframing", "prototyping",
            "user research", "usability testing", "information architecture",
            "interaction design", "visual design", "design systems",
            "user personas", "journey mapping", "card sorting",
            "heuristic evaluation", "A/B testing for design", "color theory",
            "typography", "icon design", "motion design",
            "design thinking", "accessibility design",
        ],
        "projects": [
            "Designed design system with 100+ components adopted by 5 product teams",
            "Conducted user research study with 50 participants identifying 15 usability issues",
            "Redesigned checkout flow reducing cart abandonment rate by 30%",
            "Created interactive prototypes for mobile banking app tested with 30 users",
            "Designed dashboard interface for analytics platform improving task completion by 40%",
            "Built component library in Figma with auto-layout and variant components",
            "Led design sprint resulting in validated concept for new product feature",
            "Designed accessible interface achieving WCAG 2.1 AA compliance across all screens",
        ],
        "responsibilities": [
            "Conducted user research including interviews, surveys, and usability testing sessions",
            "Created wireframes, mockups, and interactive prototypes using Figma",
            "Designed and maintained component-based design system for consistency",
            "Collaborated with product managers and engineers to define user experience",
            "Performed heuristic evaluations identifying usability improvement opportunities",
            "Presented design decisions and research findings to stakeholders",
        ],
        "summary": "Design professional focused on creating intuitive, accessible user experiences through research-driven design and systematic design systems",
    },

    "Data Engineer": {
        "skills": [
            "Apache Spark", "Apache Airflow", "Apache Kafka", "ETL pipelines",
            "data warehousing", "Snowflake", "Redshift", "BigQuery",
            "data lake architecture", "Delta Lake", "dbt", "data modeling",
            "star schema", "slowly changing dimensions", "data quality",
            "Great Expectations", "Apache Beam", "streaming data",
            "data governance", "data lineage", "data cataloging",
        ],
        "projects": [
            "Built real-time streaming pipeline processing 2M events per minute using Kafka and Spark",
            "Designed data warehouse architecture on Snowflake serving 200+ analysts",
            "Implemented data quality framework using Great Expectations across 500+ data tables",
            "Created automated ETL pipeline orchestrated by Airflow processing 10TB daily",
            "Built data lake on S3 with Delta Lake format enabling ACID transactions",
            "Designed data modeling layer using dbt transforming raw data into analytics-ready datasets",
            "Implemented change data capture pipeline for real-time database replication",
            "Built data lineage tracking system mapping data flow across 100+ pipelines",
        ],
        "responsibilities": [
            "Designed and maintained ETL pipelines transforming raw data into analytics-ready formats",
            "Built and managed data warehouse architecture supporting business intelligence needs",
            "Implemented data quality checks and monitoring for production data pipelines",
            "Optimized Spark jobs reducing processing time and compute costs by 40%",
            "Managed Apache Airflow DAGs orchestrating daily and hourly data workflows",
            "Created data models following dimensional modeling best practices",
        ],
        "summary": "Data infrastructure specialist focused on building reliable, scalable data pipelines and warehouse architectures for analytics",
    },

    "Blockchain Developer": {
        "skills": [
            "Solidity", "smart contracts", "Ethereum", "Web3.js", "Ethers.js",
            "Hardhat", "Truffle", "DeFi protocols", "ERC-20", "ERC-721",
            "NFT development", "consensus mechanisms", "IPFS",
            "decentralized applications", "Polygon", "Binance Smart Chain",
            "wallet integration", "MetaMask", "gas optimization",
            "security auditing", "reentrancy prevention", "Chainlink oracles",
        ],
        "projects": [
            "Developed DeFi lending protocol with $50M total value locked on Ethereum",
            "Created NFT marketplace smart contracts with royalty distribution system",
            "Built decentralized voting system with zero-knowledge proof verification",
            "Implemented cross-chain bridge enabling token transfers between Ethereum and Polygon",
            "Developed tokenomics model and smart contracts for DAO governance system",
            "Created automated market maker DEX with concentrated liquidity pools",
            "Built smart contract security auditing tool detecting common vulnerability patterns",
            "Developed staking platform with yield farming and reward distribution mechanisms",
        ],
        "responsibilities": [
            "Developed and deployed Solidity smart contracts on Ethereum mainnet",
            "Conducted smart contract security audits identifying reentrancy and overflow vulnerabilities",
            "Built Web3 frontend interfaces integrating MetaMask wallet connections",
            "Optimized smart contract gas consumption reducing transaction costs by 40%",
            "Implemented token standards (ERC-20, ERC-721) for various DeFi and NFT projects",
            "Maintained test suites using Hardhat achieving 100% branch coverage on critical contracts",
        ],
        "summary": "Blockchain specialist focused on smart contract development, DeFi protocols, and decentralized application architecture on Ethereum",
    },

    "Embedded Systems Engineer": {
        "skills": [
            "C", "C++ embedded", "RTOS", "FreeRTOS", "microcontrollers",
            "ARM Cortex", "STM32", "ESP32", "Arduino", "Raspberry Pi",
            "firmware development", "hardware interfaces", "SPI", "I2C", "UART",
            "IoT protocols", "MQTT", "BLE", "Zigbee",
            "oscilloscope", "logic analyzer", "PCB design",
            "interrupt handling", "DMA", "memory-mapped I/O",
        ],
        "projects": [
            "Developed firmware for wearable health monitor tracking heart rate and SpO2 in real-time",
            "Built IoT sensor network with 500+ nodes communicating via MQTT and Zigbee mesh",
            "Designed motor control firmware for industrial robot arm with 6 degrees of freedom",
            "Created bootloader for OTA firmware updates on ARM Cortex-M4 microcontrollers",
            "Developed BLE communication stack for fitness tracker with 2-week battery life",
            "Built real-time data acquisition system sampling 16 channels at 100kHz",
            "Implemented RTOS-based control system for autonomous drone flight controller",
            "Developed smart thermostat firmware with PID control and WiFi connectivity",
        ],
        "responsibilities": [
            "Developed embedded firmware in C for ARM Cortex microcontrollers",
            "Designed hardware-software interfaces using SPI, I2C, and UART protocols",
            "Debugged embedded systems using oscilloscope, logic analyzer, and JTAG debugger",
            "Implemented real-time operating system tasks with priority scheduling",
            "Optimized firmware for power consumption extending battery life by 3x",
            "Conducted hardware bring-up and board support package development",
        ],
        "summary": "Embedded specialist focused on firmware development, hardware interfaces, and real-time systems for IoT and industrial applications",
    },

    "Game Developer": {
        "skills": [
            "Unity", "Unreal Engine", "C#", "C++ game programming",
            "game physics", "shader programming", "GLSL", "HLSL",
            "3D mathematics", "collision detection", "pathfinding algorithms",
            "game AI", "behavior trees", "animation systems",
            "particle effects", "level design", "multiplayer networking",
            "game optimization", "LOD systems", "occlusion culling",
            "asset pipeline", "game audio integration",
        ],
        "projects": [
            "Developed 3D action RPG in Unity with procedural dungeon generation system",
            "Built multiplayer FPS game supporting 64 concurrent players with client-side prediction",
            "Created custom physics engine for 2D platformer with verlet integration",
            "Developed shader library with 20+ visual effects including water, fire, and particle systems",
            "Built AI system using behavior trees for NPC combat with dynamic difficulty adjustment",
            "Created mobile puzzle game achieving 1M downloads with monetization system",
            "Developed VR experience with hand tracking and spatial audio in Unreal Engine",
            "Built procedural terrain generation system with biome blending and LOD streaming",
        ],
        "responsibilities": [
            "Developed gameplay systems and mechanics using Unity and C# scripting",
            "Implemented game physics, collision detection, and character controllers",
            "Created shader programs for visual effects and material rendering",
            "Optimized game performance targeting 60fps on mobile and console platforms",
            "Designed and implemented AI behavior for NPCs using state machines and behavior trees",
            "Integrated audio systems and particle effects for immersive game experiences",
        ],
        "summary": "Game engineering specialist focused on gameplay systems, graphics programming, and real-time interactive entertainment development",
    },

    "IT Support Specialist": {
        "skills": [
            "help desk", "ticketing systems", "ServiceNow", "Zendesk",
            "troubleshooting", "hardware repair", "Windows 10/11",
            "Active Directory", "Office 365 administration", "remote support",
            "printer management", "network troubleshooting", "TCP/IP basics",
            "imaging and deployment", "MDT", "SCCM",
            "customer service", "escalation management", "SLA management",
            "antivirus management", "software installation", "VPN support",
        ],
        "projects": [
            "Managed Windows 10 to Windows 11 migration for 2000+ desktops across 5 offices",
            "Implemented ServiceNow IT service management system reducing ticket resolution time by 40%",
            "Deployed Office 365 for 1500+ users with mailbox migration from on-premise Exchange",
            "Created knowledge base with 300+ articles reducing repeat ticket volume by 35%",
            "Built automated workstation imaging process using MDT reducing setup time to 45 minutes",
            "Implemented remote support solution enabling technicians to resolve 80% of issues remotely",
            "Deployed endpoint protection solution across 3000+ endpoints with centralized management",
            "Created hardware lifecycle management program tracking 5000+ assets",
        ],
        "responsibilities": [
            "Provided tier 1 and tier 2 technical support via phone, email, and remote sessions",
            "Troubleshot hardware, software, and network issues for end users",
            "Managed Active Directory accounts including password resets and group memberships",
            "Deployed and configured workstations, laptops, and peripheral devices",
            "Maintained IT asset inventory and tracked hardware lifecycle replacements",
            "Documented solutions in knowledge base for common support issues",
        ],
        "summary": "IT support professional experienced in end-user technical support, system administration, and service desk operations",
    },

    "AI Research Scientist": {
        "skills": [
            "deep learning", "natural language processing", "computer vision",
            "transformer architectures", "attention mechanisms", "GANs",
            "reinforcement learning", "graph neural networks", "diffusion models",
            "research paper writing", "LaTeX", "peer review",
            "experiment design", "ablation studies", "benchmark evaluation",
            "PyTorch research", "JAX", "mathematical optimization",
            "linear algebra", "probability theory", "information theory",
        ],
        "projects": [
            "Published paper on novel attention mechanism achieving state-of-the-art on GLUE benchmark",
            "Developed self-supervised pretraining method reducing labeled data requirement by 80%",
            "Created multimodal model combining vision and language achieving top-5 on VQA leaderboard",
            "Designed novel graph neural network architecture for molecular property prediction",
            "Built diffusion model for high-resolution image synthesis with controllable generation",
            "Developed reinforcement learning agent achieving superhuman performance in strategy game",
            "Created few-shot learning framework generalizing to unseen classes with 5 examples",
            "Implemented efficient transformer variant with linear complexity attention mechanism",
        ],
        "responsibilities": [
            "Conducted original research in deep learning and published at top-tier conferences",
            "Designed and ran experiments with rigorous ablation studies and statistical analysis",
            "Reviewed research papers for NeurIPS, ICML, and ICLR conferences",
            "Mentored PhD students and research interns on research methodology",
            "Presented findings at international conferences and internal research seminars",
            "Collaborated with engineering teams to transfer research prototypes to production",
        ],
        "summary": "Research scientist focused on advancing the state of the art in deep learning, NLP, and computer vision through original research and publications",
    },
}
