"""
role_configs.py — Role-specific data for 25 IT profession classes.
Each role has: skills_pool, projects, responsibilities, certifications, title_variants.
"""

ROLE_CONFIG = {
    "Data Scientist": {
        "id": 0,
        "skills_pool": [
            "Python", "R", "SQL", "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy",
            "Matplotlib", "Seaborn", "Jupyter", "Spark", "Hadoop", "Statistical Modeling",
            "A/B Testing", "Hypothesis Testing", "Linear Regression", "Random Forests",
            "XGBoost", "LightGBM", "Deep Learning", "NLP", "Computer Vision",
            "Time Series", "Feature Engineering", "PCA", "Clustering", "K-Means",
            "Tableau", "Power BI", "AWS SageMaker", "BigQuery", "Azure ML",
            "Git", "Docker", "Airflow", "MLflow", "Keras", "spaCy", "Hugging Face",
        ],
        "projects": [
            "Built customer churn model using gradient boosting achieving 92% accuracy on 500K customers",
            "Developed recommendation system using collaborative filtering for 10M user e-commerce platform",
            "Created time series forecasting pipeline using ARIMA and LSTM reducing inventory costs by 15%",
            "Implemented NLP sentiment analysis pipeline using BERT processing 1M reviews daily",
            "Designed A/B testing framework across 50+ experiments driving $2M incremental revenue",
            "Built fraud detection system using anomaly detection identifying 95% fraudulent transactions",
            "Developed customer segmentation model using K-means on 2M customer records",
        ],
        "responsibilities": [
            "Led data science initiatives across product teams",
            "Built and deployed ML models to production",
            "Conducted exploratory data analysis on large datasets",
            "Designed experiments and analyzed results for product decisions",
            "Mentored junior data scientists on statistical methods",
        ],
        "certifications": ["AWS ML Specialty", "Google Data Engineer", "IBM Data Science"],
        "title_variants": ["Data Scientist", "Senior Data Scientist", "Lead Data Scientist", "Applied Scientist"],
    },
    "Software Engineer": {
        "id": 1,
        "skills_pool": [
            "Python", "Java", "C++", "Go", "Rust", "TypeScript", "JavaScript", "SQL",
            "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "REST APIs",
            "GraphQL", "gRPC", "Microservices", "AWS", "GCP", "Azure", "Docker",
            "Kubernetes", "Terraform", "CI/CD", "Jenkins", "GitHub Actions", "Git",
            "Linux", "Data Structures", "Algorithms", "System Design", "OOP",
            "Design Patterns", "SOLID", "Unit Testing", "TDD", "Agile", "Scrum",
            "Spring Boot", "Django", "FastAPI", "Kafka", "RabbitMQ", "Distributed Systems",
        ],
        "projects": [
            "Designed microservices architecture handling 100K req/sec with 99.99% uptime",
            "Developed real-time payment processing system handling $50M daily transactions",
            "Built distributed task queue using Kafka and Redis processing 5M events/hour",
            "Migrated monolith to microservices reducing deployment time from 2hr to 5min",
            "Implemented caching layer with Redis reducing API latency by 60%",
            "Designed multi-tenant SaaS platform serving 500+ enterprise customers",
            "Built search service using Elasticsearch across 100M documents",
        ],
        "responsibilities": [
            "Designed and implemented scalable backend services",
            "Led code reviews and established coding standards",
            "Optimized system performance and reduced latency",
            "Mentored junior engineers through pair programming",
            "Participated in on-call rotation for production systems",
        ],
        "certifications": ["AWS Solutions Architect", "CKA", "Oracle Java SE", "Azure Developer"],
        "title_variants": ["Software Engineer", "Senior Software Engineer", "Staff Engineer", "Backend Engineer"],
    },
    "Web Developer": {
        "id": 2,
        "skills_pool": [
            "HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Angular", "Vue.js",
            "Next.js", "Svelte", "Node.js", "Express.js", "Python", "Django", "Flask",
            "PHP", "Laravel", "SQL", "PostgreSQL", "MongoDB", "Firebase", "REST APIs",
            "GraphQL", "Tailwind CSS", "Bootstrap", "SASS", "Webpack", "Vite",
            "Jest", "Cypress", "Git", "AWS", "Vercel", "Netlify", "Docker", "Nginx",
            "Responsive Design", "PWA", "SEO", "Web Accessibility", "Redux", "OAuth",
        ],
        "projects": [
            "Built PWA e-commerce platform with 50K daily users using React and Next.js",
            "Developed real-time collaborative editor using WebSockets",
            "Created responsive dashboard with D3.js serving 200+ enterprise clients",
            "Built headless CMS website achieving 95+ Lighthouse scores",
            "Implemented design system library with 50+ components used by 10 teams",
            "Created multi-language e-learning platform with video streaming",
            "Built drag-and-drop website builder using React DnD",
        ],
        "responsibilities": [
            "Developed responsive web applications",
            "Collaborated with UX designers on pixel-perfect interfaces",
            "Optimized web performance and Core Web Vitals",
            "Implemented SEO best practices and accessibility standards",
            "Led frontend architecture decisions",
        ],
        "certifications": ["Meta Frontend Developer", "Google UX Design", "freeCodeCamp Full Stack"],
        "title_variants": ["Web Developer", "Frontend Developer", "Full Stack Developer", "UI Engineer"],
    },
    "DevOps Engineer": {
        "id": 3,
        "skills_pool": [
            "Linux", "Bash", "Python", "Go", "AWS", "GCP", "Azure", "Docker",
            "Kubernetes", "Helm", "Istio", "Terraform", "Ansible", "CloudFormation",
            "CI/CD", "Jenkins", "GitHub Actions", "GitLab CI", "ArgoCD", "Git",
            "Prometheus", "Grafana", "Datadog", "ELK Stack", "Splunk",
            "Nginx", "HAProxy", "PostgreSQL", "Redis", "Kafka", "RabbitMQ",
            "Networking", "TCP/IP", "DNS", "VPN", "IAM", "SSL/TLS", "Vault",
            "Infrastructure as Code", "SRE", "SLOs", "FinOps", "Auto-Scaling",
        ],
        "projects": [
            "Designed Kubernetes cluster managing 500+ microservices across 3 AZs",
            "Built CI/CD pipeline reducing deployment from 4hr to 15min using ArgoCD",
            "Migrated on-prem to AWS reducing costs 40% improving uptime to 99.99%",
            "Implemented IaC with Terraform managing 200+ resources across 5 environments",
            "Built centralized logging platform using ELK processing 50GB logs daily",
            "Implemented auto-scaling reducing cloud costs $500K annually",
            "Created chaos engineering framework for resilience testing",
        ],
        "responsibilities": [
            "Managed cloud infrastructure across multiple environments",
            "Designed CI/CD pipelines for development teams",
            "Monitored system health and resolved production incidents",
            "Automated infrastructure provisioning and configuration",
            "Led incident response and post-mortem processes",
        ],
        "certifications": ["AWS DevOps Professional", "CKA", "Terraform Associate", "RHCSA"],
        "title_variants": ["DevOps Engineer", "Senior DevOps Engineer", "SRE", "Cloud Engineer"],
    },
    "ML Engineer": {
        "id": 4,
        "skills_pool": [
            "Python", "C++", "PyTorch", "TensorFlow", "JAX", "Keras", "Scikit-learn",
            "XGBoost", "Hugging Face", "ONNX", "TensorRT", "NLP", "Computer Vision",
            "BERT", "GPT", "T5", "LLMs", "CNNs", "RNNs", "Transformers", "GANs",
            "MLflow", "Kubeflow", "MLOps", "Docker", "Kubernetes", "AWS SageMaker",
            "Distributed Training", "Model Optimization", "Quantization", "CUDA",
            "GPU Programming", "Mixed Precision", "Git", "DVC", "W&B",
            "FastAPI", "Flask", "gRPC", "SQL", "Spark", "Ray", "Airflow",
        ],
        "projects": [
            "Built ML pipeline for real-time fraud detection at 10K TPS with 99.7% accuracy",
            "Deployed BERT NLP model serving 5M API requests daily with <50ms latency",
            "Developed CV pipeline for autonomous vehicle detection using YOLOv5 with 95% mAP",
            "Implemented model serving with TF Serving handling 100K inferences/sec",
            "Fine-tuned GPT models for domain text generation reducing content costs 60%",
            "Built model monitoring system tracking drift across 50+ production models",
            "Implemented distributed training on 8 GPUs reducing training time 6x",
        ],
        "responsibilities": [
            "Designed production ML systems end-to-end",
            "Optimized model inference latency and throughput",
            "Built ML infrastructure and pipelines",
            "Implemented model monitoring and alerting",
            "Led MLOps practices and model lifecycle management",
        ],
        "certifications": ["AWS ML Specialty", "Google ML Engineer", "NVIDIA DLI", "TF Developer"],
        "title_variants": ["ML Engineer", "Senior ML Engineer", "AI Engineer", "MLOps Engineer"],
    },
    "Data Analyst": {
        "id": 5,
        "skills_pool": [
            "SQL", "Python", "R", "Excel", "Tableau", "Power BI", "Looker", "Google Analytics",
            "Pandas", "NumPy", "Matplotlib", "Seaborn", "Statistical Analysis", "A/B Testing",
            "Data Visualization", "ETL", "Data Cleaning", "Data Modeling", "BigQuery",
            "Redshift", "Snowflake", "dbt", "Airflow", "JIRA", "Confluence",
            "Regression Analysis", "Dashboard Design", "KPI Tracking", "Reporting",
            "Storytelling with Data", "Hypothesis Testing", "Cohort Analysis",
        ],
        "projects": [
            "Built executive dashboard tracking 20+ KPIs across 5 business units",
            "Developed customer cohort analysis reducing churn by 12%",
            "Created automated ETL pipeline processing 10M records daily",
            "Designed A/B testing framework improving conversion rates by 18%",
            "Built sales forecasting model with 90% accuracy using time series analysis",
            "Developed marketing attribution model identifying top-performing channels",
        ],
        "responsibilities": [
            "Analyzed business data to identify trends and insights",
            "Created dashboards and reports for stakeholders",
            "Collaborated with product teams on data-driven decisions",
            "Maintained data quality and documentation",
            "Automated recurring reports and data pipelines",
        ],
        "certifications": ["Google Data Analytics", "Tableau Desktop Specialist", "Microsoft PL-300"],
        "title_variants": ["Data Analyst", "Senior Data Analyst", "Business Intelligence Analyst", "Analytics Engineer"],
    },
    "Backend Developer": {
        "id": 6,
        "skills_pool": [
            "Python", "Java", "Go", "Node.js", "C#", "Ruby", "Rust",
            "Django", "Flask", "FastAPI", "Spring Boot", "Express.js", ".NET",
            "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "DynamoDB",
            "REST APIs", "GraphQL", "gRPC", "WebSockets", "Microservices",
            "Docker", "Kubernetes", "AWS", "GCP", "CI/CD", "Git",
            "Message Queues", "Kafka", "RabbitMQ", "Caching", "Load Balancing",
            "OAuth", "JWT", "SQL", "ORM", "Database Design", "API Design",
        ],
        "projects": [
            "Built high-throughput API gateway handling 200K req/sec",
            "Designed event-driven architecture processing 10M events daily",
            "Implemented database sharding for 1TB+ dataset with sub-100ms queries",
            "Built real-time notification service for 5M users",
            "Developed payment processing backend handling $100M annually",
            "Created API versioning strategy for 50+ consumer applications",
        ],
        "responsibilities": [
            "Designed and built RESTful and GraphQL APIs",
            "Optimized database queries and schema design",
            "Implemented authentication and authorization systems",
            "Managed service deployments and infrastructure",
            "Wrote comprehensive API documentation",
        ],
        "certifications": ["AWS Developer Associate", "Oracle Java SE", "MongoDB Developer"],
        "title_variants": ["Backend Developer", "Senior Backend Developer", "API Engineer", "Server-Side Developer"],
    },
    "Frontend Developer": {
        "id": 7,
        "skills_pool": [
            "JavaScript", "TypeScript", "React", "Angular", "Vue.js", "Next.js", "Svelte",
            "HTML5", "CSS3", "SASS", "Tailwind CSS", "Material UI", "Styled Components",
            "Redux", "Zustand", "MobX", "React Query", "Webpack", "Vite", "Babel",
            "Jest", "React Testing Library", "Cypress", "Playwright",
            "Responsive Design", "Accessibility", "WCAG", "SEO", "PWA",
            "Figma", "Storybook", "Design Systems", "Performance Optimization",
            "Web APIs", "Service Workers", "Git", "npm", "yarn",
        ],
        "projects": [
            "Built component library with 100+ reusable components and Storybook docs",
            "Developed real-time collaborative whiteboard using Canvas API",
            "Created accessible design system meeting WCAG 2.1 AA standards",
            "Built micro-frontend architecture for enterprise platform",
            "Implemented offline-first PWA with background sync",
            "Optimized bundle size by 60% through code splitting and lazy loading",
        ],
        "responsibilities": [
            "Built pixel-perfect UI components from design specs",
            "Implemented state management for complex applications",
            "Optimized rendering performance and bundle sizes",
            "Ensured cross-browser compatibility and accessibility",
            "Collaborated with designers on component specifications",
        ],
        "certifications": ["Meta Frontend Developer", "Google Mobile Web Specialist"],
        "title_variants": ["Frontend Developer", "Senior Frontend Developer", "UI Engineer", "React Developer"],
    },
    "Full Stack Developer": {
        "id": 8,
        "skills_pool": [
            "JavaScript", "TypeScript", "Python", "Java", "React", "Angular", "Vue.js",
            "Next.js", "Node.js", "Express.js", "Django", "Flask", "Spring Boot",
            "HTML5", "CSS3", "Tailwind CSS", "PostgreSQL", "MongoDB", "Redis",
            "REST APIs", "GraphQL", "Docker", "AWS", "GCP", "Vercel", "Git",
            "CI/CD", "Jest", "Cypress", "Agile", "Scrum", "OAuth", "JWT",
            "Microservices", "Serverless", "Firebase", "Prisma", "TypeORM",
        ],
        "projects": [
            "Built SaaS platform serving 10K users with React frontend and Node.js backend",
            "Developed real-time marketplace with payment integration and chat system",
            "Created project management tool with drag-and-drop Kanban boards",
            "Built social media analytics dashboard with real-time data streaming",
            "Developed multi-tenant CRM system with role-based access control",
            "Created automated deployment pipeline with preview environments",
        ],
        "responsibilities": [
            "Developed both frontend and backend features end-to-end",
            "Designed database schemas and API contracts",
            "Managed cloud infrastructure and deployments",
            "Conducted code reviews across the full stack",
            "Collaborated with designers and product managers",
        ],
        "certifications": ["AWS Developer Associate", "Meta Full Stack Certificate"],
        "title_variants": ["Full Stack Developer", "Senior Full Stack Developer", "Software Developer"],
    },
    "Database Administrator": {
        "id": 9,
        "skills_pool": [
            "PostgreSQL", "MySQL", "Oracle", "SQL Server", "MongoDB", "Redis",
            "Cassandra", "DynamoDB", "Elasticsearch", "SQL", "PL/SQL", "T-SQL",
            "Database Design", "Schema Optimization", "Query Tuning", "Indexing",
            "Backup and Recovery", "Replication", "Sharding", "Partitioning",
            "High Availability", "Disaster Recovery", "Performance Monitoring",
            "AWS RDS", "Azure SQL", "Google Cloud SQL", "Terraform",
            "Python", "Bash", "Shell Scripting", "Data Migration", "ETL",
        ],
        "projects": [
            "Managed 50TB PostgreSQL cluster with 99.999% uptime across 3 regions",
            "Designed sharding strategy reducing query latency from 500ms to 20ms",
            "Migrated legacy Oracle database to PostgreSQL saving $200K annually",
            "Implemented automated backup system with point-in-time recovery",
            "Built real-time replication across 5 data centers",
            "Optimized slow queries improving application performance by 40%",
        ],
        "responsibilities": [
            "Managed database performance tuning and optimization",
            "Implemented backup, recovery and disaster recovery plans",
            "Designed database schemas and data models",
            "Monitored database health and resolved incidents",
            "Managed database migrations and upgrades",
        ],
        "certifications": ["Oracle DBA Certified", "AWS Database Specialty", "MongoDB DBA"],
        "title_variants": ["Database Administrator", "Senior DBA", "Database Engineer", "Data Platform Engineer"],
    },
    "System Administrator": {
        "id": 10,
        "skills_pool": [
            "Linux", "Windows Server", "Ubuntu", "CentOS", "RHEL", "Bash",
            "PowerShell", "Python", "Active Directory", "LDAP", "DNS", "DHCP",
            "Networking", "TCP/IP", "Firewalls", "VPN", "VMware", "Hyper-V",
            "Ansible", "Puppet", "Chef", "Nagios", "Zabbix", "SNMP",
            "AWS", "Azure", "Backup Solutions", "Disaster Recovery",
            "Security Hardening", "Patch Management", "ITIL", "Help Desk",
        ],
        "projects": [
            "Managed 500+ server infrastructure across 3 data centers",
            "Automated server provisioning reducing setup from 2 days to 30 min",
            "Implemented centralized log management with 99.9% uptime",
            "Designed disaster recovery plan with RPO<1hr and RTO<4hr",
            "Migrated 200+ VMs from on-prem to AWS cloud",
            "Built automated patch management system for 1000+ endpoints",
        ],
        "responsibilities": [
            "Managed server infrastructure and operating systems",
            "Automated routine tasks with scripting",
            "Monitored system performance and availability",
            "Managed user accounts and access permissions",
            "Maintained documentation and runbooks",
        ],
        "certifications": ["RHCSA", "CompTIA Server+", "Microsoft MCSA", "AWS SysOps"],
        "title_variants": ["System Administrator", "Senior Sysadmin", "Linux Administrator", "IT Administrator"],
    },
    "Network Engineer": {
        "id": 11,
        "skills_pool": [
            "Cisco IOS", "Juniper", "TCP/IP", "BGP", "OSPF", "MPLS", "VLAN",
            "Firewalls", "VPN", "IPSec", "SSL/TLS", "DNS", "DHCP", "NAT",
            "Load Balancing", "F5", "Palo Alto", "Fortinet", "Wireshark",
            "SDN", "Network Automation", "Ansible", "Python", "SNMP", "NetFlow",
            "AWS VPC", "Azure Networking", "Cloud Networking", "WiFi", "802.11",
            "Network Security", "IDS/IPS", "Network Monitoring", "Nagios", "SolarWinds",
        ],
        "projects": [
            "Designed enterprise WAN connecting 50 offices across 10 countries",
            "Implemented SD-WAN reducing bandwidth costs by 40%",
            "Built network automation framework managing 2000+ devices",
            "Designed zero-trust network architecture for 5000 employees",
            "Migrated network infrastructure to cloud-managed SD-WAN",
            "Implemented network segmentation reducing attack surface by 60%",
        ],
        "responsibilities": [
            "Designed and maintained enterprise network infrastructure",
            "Configured routers, switches, and firewalls",
            "Troubleshot network connectivity issues",
            "Implemented network security policies",
            "Managed network monitoring and alerting",
        ],
        "certifications": ["CCNA", "CCNP", "JNCIA", "CompTIA Network+", "AWS Networking Specialty"],
        "title_variants": ["Network Engineer", "Senior Network Engineer", "Network Architect", "Network Administrator"],
    },
    "Cybersecurity Analyst": {
        "id": 12,
        "skills_pool": [
            "SIEM", "Splunk", "QRadar", "Incident Response", "Threat Hunting",
            "Vulnerability Assessment", "Penetration Testing", "Nessus", "Burp Suite",
            "Metasploit", "Wireshark", "Firewalls", "IDS/IPS", "Endpoint Security",
            "OWASP", "Malware Analysis", "Forensics", "SOC", "Risk Assessment",
            "Compliance", "NIST", "ISO 27001", "GDPR", "PCI-DSS", "HIPAA",
            "Python", "Bash", "PowerShell", "AWS Security", "Azure Security",
            "Identity Management", "Zero Trust", "Encryption", "PKI",
        ],
        "projects": [
            "Built SOC monitoring 10K+ events/sec from 500+ sources",
            "Led incident response for ransomware attack containing breach in 4 hours",
            "Implemented vulnerability management program reducing critical vulns by 80%",
            "Designed zero-trust architecture for 10K employee organization",
            "Developed automated threat detection using ML reducing false positives 60%",
            "Led PCI-DSS compliance audit achieving Level 1 certification",
        ],
        "responsibilities": [
            "Monitored security events and alerts",
            "Conducted vulnerability assessments and pen tests",
            "Led incident response and forensic investigations",
            "Developed security policies and procedures",
            "Managed security tools and infrastructure",
        ],
        "certifications": ["CISSP", "CEH", "CompTIA Security+", "OSCP", "AWS Security Specialty"],
        "title_variants": ["Cybersecurity Analyst", "Security Engineer", "SOC Analyst", "InfoSec Analyst"],
    },
    "Cloud Architect": {
        "id": 13,
        "skills_pool": [
            "AWS", "Azure", "GCP", "Multi-Cloud", "Cloud Architecture", "Well-Architected",
            "EC2", "S3", "Lambda", "EKS", "RDS", "VPC", "CloudFront", "Route 53",
            "Terraform", "CloudFormation", "Pulumi", "Docker", "Kubernetes",
            "Serverless", "Microservices", "Event-Driven", "Cost Optimization",
            "Security Architecture", "IAM", "Networking", "Load Balancing",
            "Disaster Recovery", "High Availability", "Auto-Scaling", "FinOps",
            "Python", "Go", "CI/CD", "Monitoring", "Observability",
        ],
        "projects": [
            "Designed multi-region cloud architecture serving 10M users globally",
            "Led cloud migration of 200+ applications saving $2M annually",
            "Built serverless data processing pipeline handling 1TB daily",
            "Designed disaster recovery strategy with RPO<5min across 3 regions",
            "Implemented cloud cost optimization reducing spend by 35%",
            "Architected container platform serving 500+ microservices",
        ],
        "responsibilities": [
            "Designed cloud architecture for enterprise applications",
            "Led cloud migration and modernization initiatives",
            "Established cloud governance and best practices",
            "Optimized cloud costs and resource utilization",
            "Evaluated cloud services and made technology recommendations",
        ],
        "certifications": ["AWS Solutions Architect Pro", "Azure Solutions Architect", "GCP Cloud Architect"],
        "title_variants": ["Cloud Architect", "Senior Cloud Architect", "Cloud Solutions Architect", "Cloud Engineer"],
    },
    "QA Engineer": {
        "id": 14,
        "skills_pool": [
            "Selenium", "Cypress", "Playwright", "Appium", "JUnit", "TestNG",
            "Pytest", "Jest", "Postman", "API Testing", "REST Assured",
            "Performance Testing", "JMeter", "Gatling", "LoadRunner",
            "Test Automation", "CI/CD Testing", "Jenkins", "GitHub Actions",
            "Python", "Java", "JavaScript", "SQL", "Git", "JIRA",
            "Agile Testing", "BDD", "Cucumber", "Test Planning", "Bug Tracking",
            "Mobile Testing", "Cross-Browser Testing", "Accessibility Testing",
        ],
        "projects": [
            "Built end-to-end test automation framework covering 2000+ test cases",
            "Implemented API testing suite with 95% endpoint coverage",
            "Created performance testing pipeline catching regressions before release",
            "Built visual regression testing system comparing 500+ UI components",
            "Developed mobile testing framework for iOS and Android apps",
            "Implemented shift-left testing reducing production bugs by 70%",
        ],
        "responsibilities": [
            "Designed and maintained test automation frameworks",
            "Created test plans and test cases for new features",
            "Performed manual and automated testing",
            "Reported and tracked defects through resolution",
            "Collaborated with developers on quality improvements",
        ],
        "certifications": ["ISTQB Foundation", "AWS Certified", "Selenium WebDriver Cert"],
        "title_variants": ["QA Engineer", "Senior QA Engineer", "SDET", "Test Automation Engineer"],
    },
    "Mobile App Developer": {
        "id": 15,
        "skills_pool": [
            "Swift", "Kotlin", "React Native", "Flutter", "Dart", "Java",
            "Objective-C", "SwiftUI", "Jetpack Compose", "Xcode", "Android Studio",
            "iOS", "Android", "Cross-Platform", "REST APIs", "GraphQL",
            "SQLite", "Realm", "Firebase", "Core Data", "Room",
            "Push Notifications", "In-App Purchases", "App Store", "Google Play",
            "CI/CD", "Fastlane", "TestFlight", "Git", "Figma",
            "Performance Optimization", "Offline Storage", "Bluetooth", "AR/VR",
        ],
        "projects": [
            "Built fintech app with 500K downloads and 4.8 star rating",
            "Developed cross-platform social app using React Native for iOS and Android",
            "Created health tracking app with HealthKit and Google Fit integration",
            "Built real-time messaging app with end-to-end encryption",
            "Developed AR shopping experience using ARKit increasing engagement 40%",
            "Created offline-first app with background sync for field workers",
        ],
        "responsibilities": [
            "Developed native and cross-platform mobile applications",
            "Published apps to App Store and Google Play",
            "Optimized app performance and battery usage",
            "Implemented push notifications and deep linking",
            "Collaborated with designers on mobile UX patterns",
        ],
        "certifications": ["Google Android Developer", "Apple Developer Cert", "Flutter Developer"],
        "title_variants": ["Mobile Developer", "iOS Developer", "Android Developer", "React Native Developer"],
    },
    "Business Analyst": {
        "id": 16,
        "skills_pool": [
            "Requirements Gathering", "Business Process Modeling", "Use Case Analysis",
            "User Stories", "Acceptance Criteria", "UML", "BPMN", "Wireframing",
            "SQL", "Excel", "Tableau", "Power BI", "JIRA", "Confluence",
            "Agile", "Scrum", "Kanban", "Waterfall", "Stakeholder Management",
            "Data Analysis", "Process Improvement", "Gap Analysis", "ROI Analysis",
            "Documentation", "Presentations", "Communication", "Problem Solving",
            "Python", "SAP", "Salesforce", "CRM", "ERP",
        ],
        "projects": [
            "Led requirements for CRM migration serving 5000 users across 10 departments",
            "Documented 50+ business processes identifying $1M in efficiency gains",
            "Created product roadmap aligning business goals with technical capabilities",
            "Designed data migration strategy for ERP system consolidation",
            "Developed KPI dashboard for executive decision making",
            "Led UAT coordination for 200+ test scenarios across 3 releases",
        ],
        "responsibilities": [
            "Gathered and documented business requirements",
            "Facilitated workshops with stakeholders",
            "Created user stories and acceptance criteria",
            "Conducted gap analysis and process mapping",
            "Supported UAT and go-live activities",
        ],
        "certifications": ["CBAP", "PMI-PBA", "SAFe Agilist", "Certified Scrum Master"],
        "title_variants": ["Business Analyst", "Senior Business Analyst", "Systems Analyst", "Product Analyst"],
    },
    "IT Project Manager": {
        "id": 17,
        "skills_pool": [
            "Project Management", "Agile", "Scrum", "Kanban", "Waterfall", "SAFe",
            "JIRA", "Confluence", "MS Project", "Asana", "Monday.com",
            "Risk Management", "Budget Management", "Resource Planning",
            "Stakeholder Management", "Vendor Management", "Change Management",
            "PMP", "Program Management", "Portfolio Management",
            "Sprint Planning", "Retrospectives", "Standups", "Release Planning",
            "Technical Writing", "Presentations", "Communication", "Leadership",
            "ServiceNow", "Gantt Charts", "WBS", "Critical Path",
        ],
        "projects": [
            "Managed $5M digital transformation program across 8 teams and 50+ engineers",
            "Led cloud migration project delivering 200+ applications on time and under budget",
            "Managed agile transformation for 100-person engineering organization",
            "Coordinated cross-functional launch of SaaS product with 50K initial users",
            "Led disaster recovery project achieving RPO/RTO compliance",
            "Managed vendor integration project consolidating 5 platforms into 1",
        ],
        "responsibilities": [
            "Managed project timelines, budgets, and resources",
            "Facilitated agile ceremonies and sprint planning",
            "Communicated project status to stakeholders",
            "Identified and mitigated project risks",
            "Coordinated cross-functional teams and dependencies",
        ],
        "certifications": ["PMP", "CSM", "SAFe Agilist", "PRINCE2", "ITIL Foundation"],
        "title_variants": ["IT Project Manager", "Senior PM", "Scrum Master", "Program Manager", "Technical PM"],
    },
    "UI/UX Designer": {
        "id": 18,
        "skills_pool": [
            "Figma", "Sketch", "Adobe XD", "InVision", "Framer", "Principle",
            "User Research", "Usability Testing", "A/B Testing", "Heuristic Evaluation",
            "Wireframing", "Prototyping", "Information Architecture", "User Flows",
            "Design Systems", "Component Libraries", "Typography", "Color Theory",
            "Interaction Design", "Motion Design", "Responsive Design", "Mobile Design",
            "HTML", "CSS", "JavaScript", "Accessibility", "WCAG",
            "User Personas", "Journey Mapping", "Card Sorting", "Analytics",
            "Miro", "FigJam", "Zeplin", "Abstract",
        ],
        "projects": [
            "Redesigned enterprise SaaS platform increasing user engagement by 35%",
            "Created design system with 200+ components used across 5 product teams",
            "Led user research program interviewing 100+ users for product discovery",
            "Designed mobile banking app achieving 4.8 star rating with 1M downloads",
            "Built accessibility-first design framework meeting WCAG 2.1 AAA standards",
            "Designed onboarding flow reducing time-to-value by 50%",
        ],
        "responsibilities": [
            "Conducted user research and usability testing",
            "Created wireframes, prototypes and high-fidelity designs",
            "Built and maintained design systems",
            "Collaborated with engineers on implementation",
            "Presented design rationale to stakeholders",
        ],
        "certifications": ["Google UX Design", "Nielsen Norman UX", "Interaction Design Foundation"],
        "title_variants": ["UI/UX Designer", "Senior UX Designer", "Product Designer", "UX Researcher"],
    },
    "Data Engineer": {
        "id": 19,
        "skills_pool": [
            "Python", "SQL", "Spark", "Hadoop", "Hive", "Presto", "Flink",
            "Kafka", "Airflow", "dbt", "Prefect", "Dagster", "Luigi",
            "AWS Glue", "Redshift", "BigQuery", "Snowflake", "Databricks",
            "S3", "GCS", "Delta Lake", "Parquet", "Avro",
            "ETL", "ELT", "Data Modeling", "Data Warehousing", "Data Lakes",
            "Batch Processing", "Stream Processing", "Data Quality",
            "Docker", "Kubernetes", "Terraform", "Git", "CI/CD",
            "PostgreSQL", "MySQL", "MongoDB", "Cassandra", "Redis",
        ],
        "projects": [
            "Built data platform processing 5TB daily across 200+ data sources",
            "Designed real-time streaming pipeline with Kafka handling 1M events/sec",
            "Migrated data warehouse from Redshift to Snowflake reducing costs 45%",
            "Built data quality framework catching 99.9% of data anomalies",
            "Created feature store serving ML models with sub-10ms latency",
            "Designed data lakehouse architecture on Delta Lake",
        ],
        "responsibilities": [
            "Built and maintained data pipelines and ETL processes",
            "Designed data warehouse schemas and models",
            "Optimized query performance and data processing",
            "Ensured data quality and reliability",
            "Collaborated with analysts and scientists on data needs",
        ],
        "certifications": ["AWS Data Analytics Specialty", "Google Data Engineer", "Databricks Engineer"],
        "title_variants": ["Data Engineer", "Senior Data Engineer", "Platform Data Engineer", "Analytics Engineer"],
    },
    "Blockchain Developer": {
        "id": 20,
        "skills_pool": [
            "Solidity", "Ethereum", "Web3.js", "Ethers.js", "Hardhat", "Truffle",
            "Smart Contracts", "DeFi", "NFT", "ERC-20", "ERC-721", "ERC-1155",
            "IPFS", "Chainlink", "OpenZeppelin", "Polygon", "Avalanche", "Solana",
            "Rust", "Python", "JavaScript", "TypeScript", "Go",
            "Cryptography", "Consensus Mechanisms", "Token Economics",
            "React", "Next.js", "Node.js", "GraphQL", "MongoDB",
            "Security Auditing", "Gas Optimization", "Unit Testing",
        ],
        "projects": [
            "Built DeFi lending protocol with $50M TVL on Ethereum",
            "Developed NFT marketplace handling 10K transactions daily",
            "Created cross-chain bridge supporting 5 blockchain networks",
            "Built DAO governance system with on-chain voting for 10K members",
            "Developed smart contract auditing tool catching common vulnerabilities",
            "Created token launchpad platform facilitating 100+ token launches",
        ],
        "responsibilities": [
            "Developed and deployed smart contracts",
            "Built decentralized applications (dApps)",
            "Conducted security audits on smart contracts",
            "Optimized gas costs and transaction efficiency",
            "Integrated blockchain solutions with web frontends",
        ],
        "certifications": ["Certified Blockchain Developer", "Ethereum Developer", "ConsenSys Academy"],
        "title_variants": ["Blockchain Developer", "Smart Contract Developer", "Web3 Developer", "DeFi Engineer"],
    },
    "Embedded Systems Engineer": {
        "id": 21,
        "skills_pool": [
            "C", "C++", "Embedded C", "Assembly", "Python", "Rust",
            "RTOS", "FreeRTOS", "Zephyr", "Linux Kernel", "Device Drivers",
            "ARM", "Cortex-M", "RISC-V", "FPGA", "Verilog", "VHDL",
            "SPI", "I2C", "UART", "CAN", "Ethernet", "WiFi", "Bluetooth",
            "PCB Design", "Altium", "KiCad", "Oscilloscope", "Logic Analyzer",
            "IoT", "MQTT", "CoAP", "Edge Computing", "Sensors", "Actuators",
            "Git", "CMake", "GDB", "JTAG", "CI/CD",
        ],
        "projects": [
            "Developed firmware for IoT sensor platform monitoring 10K industrial devices",
            "Designed real-time motor control system with 1kHz control loop",
            "Built OTA firmware update system for 50K deployed devices",
            "Developed driver stack for custom ASIC with 5 peripheral interfaces",
            "Created edge ML inference engine running on Cortex-M4 at 30fps",
            "Designed power management system extending battery life from 6 to 18 months",
        ],
        "responsibilities": [
            "Developed embedded firmware for microcontrollers",
            "Designed hardware-software interfaces",
            "Debugged and optimized real-time systems",
            "Managed firmware release cycles and testing",
            "Collaborated with hardware engineers on PCB designs",
        ],
        "certifications": ["ARM Certified Engineer", "CompTIA A+", "Embedded Linux Professional"],
        "title_variants": ["Embedded Engineer", "Firmware Engineer", "IoT Engineer", "Hardware Engineer"],
    },
    "Game Developer": {
        "id": 22,
        "skills_pool": [
            "Unity", "Unreal Engine", "C#", "C++", "Python", "Lua",
            "Game Design", "Level Design", "3D Modeling", "Animation",
            "Blender", "Maya", "Substance Painter", "Photoshop",
            "Physics Engine", "AI Pathfinding", "Shader Programming", "HLSL", "GLSL",
            "Multiplayer Networking", "Dedicated Servers", "P2P", "Photon",
            "Mobile Games", "PC Games", "Console Games", "VR/AR",
            "Git", "Perforce", "Agile", "Scrum", "Version Control",
            "Sound Design", "UI/UX for Games", "Performance Optimization",
        ],
        "projects": [
            "Developed mobile RPG game with 1M downloads and 4.5 star rating",
            "Built multiplayer FPS with dedicated servers supporting 64 players",
            "Created VR training simulation for medical education",
            "Designed procedural level generation system for roguelike game",
            "Built custom physics engine for racing game achieving 60fps on mobile",
            "Developed AI system with behavior trees for 100+ NPC characters",
        ],
        "responsibilities": [
            "Developed gameplay systems and mechanics",
            "Implemented game AI and pathfinding",
            "Optimized game performance across platforms",
            "Collaborated with artists on asset integration",
            "Fixed bugs and balanced gameplay",
        ],
        "certifications": ["Unity Certified Developer", "Unreal Engine Cert", "Game Design Certificate"],
        "title_variants": ["Game Developer", "Game Programmer", "Gameplay Engineer", "Game Designer"],
    },
    "IT Support Specialist": {
        "id": 23,
        "skills_pool": [
            "Windows", "macOS", "Linux", "Active Directory", "Office 365",
            "Google Workspace", "Networking", "TCP/IP", "DNS", "DHCP", "VPN",
            "Help Desk", "ServiceNow", "Zendesk", "Freshdesk", "Ticketing Systems",
            "Troubleshooting", "Hardware Repair", "Printer Management",
            "Remote Desktop", "TeamViewer", "MDM", "Jamf", "Intune",
            "Backup Solutions", "Antivirus", "Endpoint Security",
            "ITIL", "Customer Service", "Communication", "Documentation",
            "PowerShell", "Bash", "Basic Python",
        ],
        "projects": [
            "Managed IT support for 2000+ employee organization across 10 offices",
            "Led Windows 11 migration for 1500 workstations with zero downtime",
            "Implemented MDM solution for 3000 mobile devices",
            "Built self-service IT portal reducing ticket volume by 30%",
            "Designed onboarding automation provisioning accounts in <1 hour",
            "Created knowledge base with 500+ articles reducing repeat tickets 40%",
        ],
        "responsibilities": [
            "Provided Level 1-3 technical support to end users",
            "Managed hardware and software inventory",
            "Configured and deployed workstations and laptops",
            "Troubleshot network and connectivity issues",
            "Maintained IT documentation and knowledge base",
        ],
        "certifications": ["CompTIA A+", "CompTIA Network+", "ITIL Foundation", "Microsoft 365 Certified"],
        "title_variants": ["IT Support Specialist", "Help Desk Technician", "IT Technician", "Desktop Support"],
    },
    "AI Research Scientist": {
        "id": 24,
        "skills_pool": [
            "Python", "C++", "PyTorch", "TensorFlow", "JAX", "NumPy",
            "Deep Learning", "Reinforcement Learning", "Generative AI", "LLMs",
            "Transformers", "Attention Mechanisms", "Diffusion Models", "GANs",
            "NLP", "Computer Vision", "Speech Processing", "Multimodal AI",
            "BERT", "GPT", "LLaMA", "CLIP", "Stable Diffusion", "RLHF",
            "Research Publication", "LaTeX", "Academic Writing",
            "Distributed Training", "CUDA", "GPU Clusters", "HPC",
            "Statistics", "Linear Algebra", "Optimization", "Probability Theory",
            "Git", "Docker", "Experiment Tracking", "W&B", "MLflow",
        ],
        "projects": [
            "Published 5 papers at NeurIPS/ICML on novel attention mechanisms",
            "Developed new training technique for LLMs reducing compute costs by 30%",
            "Created multimodal AI system combining vision and language understanding",
            "Designed novel architecture for efficient inference on edge devices",
            "Led research on RLHF improving LLM alignment on safety benchmarks",
            "Developed self-supervised learning method achieving SOTA on ImageNet",
        ],
        "responsibilities": [
            "Conducted research on novel ML architectures",
            "Published papers at top conferences",
            "Implemented and evaluated experimental models",
            "Mentored junior researchers and PhD students",
            "Collaborated with engineering teams on research-to-production",
        ],
        "certifications": ["Ph.D. in ML/AI", "Stanford ML Certificate", "DeepMind Scholar"],
        "title_variants": ["AI Research Scientist", "Research Scientist", "ML Researcher", "Applied Research Scientist"],
    },
}
